version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    ignore:
        update-types: ["version-update:semver-major"]
