pluginManagement {
    includeBuild("tooling")
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

rootProject.name = "Store5"

include ':store'
include ':cache'
include ':multicast'
include ':rx2'
include ':core'
include ':store6-core'
include ':store6-quickstart'
include ':store6-swift-dumps-objc'
project(':store6-swift-dumps-objc').projectDir = file('store6-swift-dumps/objc')
include ':store6-swift-dumps-skie'
project(':store6-swift-dumps-skie').projectDir = file('store6-swift-dumps/skie')
include ':store6-extension-probe'
include ':store6-testing'
include ':store6-sqldelight'
include ':store6-sqldelight-sample'
project(':store6-sqldelight-sample').projectDir = file('store6-sqldelight/sample')
include ':store6-compose'
include ':store6-compose-demo'
include ':store6-room'
include ':store6-room-sample'
project(':store6-room-sample').projectDir = file('store6-room/sample')
include ':store6-benchmarks'
include ':store6-devtools'
include ':store6-devtools-inspector'
include ':store6-devtools-demo'
include ':store6-mutations'
