pluginManagement {
    includeBuild("tooling")
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

rootProject.name = "Store5"

include ':core'
include ':quickstart'
include ':swift-dumps-objc'
project(':swift-dumps-objc').projectDir = file('swift-dumps/objc')
include ':swift-dumps-skie'
project(':swift-dumps-skie').projectDir = file('swift-dumps/skie')
include ':swift-dumps-mutations-objc'
project(':swift-dumps-mutations-objc').projectDir = file('swift-dumps/mutations-objc')
include ':swift-dumps-mutations-skie'
project(':swift-dumps-mutations-skie').projectDir = file('swift-dumps/mutations-skie')
include ':extension-probe'
include ':testing'
include ':sqldelight'
include ':sqldelight-sample'
project(':sqldelight-sample').projectDir = file('sqldelight/sample')
include ':compose'
include ':compose-demo'
include ':room'
include ':room-sample'
project(':room-sample').projectDir = file('room/sample')
include ':paging-androidx'
include ':paging-androidx-sample'
project(':paging-androidx-sample').projectDir = file('paging-androidx/sample')
include ':graphql'
include ':graphql-sample'
project(':graphql-sample').projectDir = file('graphql/sample')
include ':realtime'
include ':realtime-sample'
project(':realtime-sample').projectDir = file('realtime/sample')
include ':benchmarks'
include ':devtools'
include ':devtools-inspector'
include ':devtools-demo'
include ':mutations'
include ':mutations-quickstart'
include ':mutations-testing'
include ':mutations-sqldelight'
