complexity:
  active: true
  CyclomaticComplexMethod:
    active: false
  LargeClass:
    active: false
  LongMethod:
    active: false
  LongParameterList:
    active: false
  NestedBlockDepth:
    active: false
  TooManyFunctions:
    active: false

empty-blocks:
  active: true
  EmptyDefaultConstructor:
    active: false
  EmptyFunctionBlock:
    active: false

exceptions:
  active: true
  InstanceOfCheckForException:
    active: false
  SwallowedException:
    active: false
  TooGenericExceptionCaught:
    active: false
  TooGenericExceptionThrown:
    active: false

style:
  active: true
  ExplicitItLambdaParameter:
    active: false
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  MayBeConst:
    active: false
  ReturnCount:
    active: false
  UnusedParameter:
    active: false
  UnusedPrivateMember:
    active: false
  UnusedPrivateProperty:
    active: false
  UseCheckOrError:
    active: false
  UseRequire:
    active: false
