name: Check
on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run check with Gradle Wrapper
        run: ./gradlew check