name: Check
on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run check with Gradle Wrapper
        run: ./gradlew check

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v3
        with:
          files: ./kover/coverage.xml
          name: codecov-umbrella
          verbose: true