name: Codecov
on: [ push, pull_request ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v3
        with:
          files: ./kover/coverage.xml
          name: codecov-umbrella
          verbose: true