# Publish a build for development. The Xcode framework is debuggable.
name: KMMBridge-Debug
on:
  workflow_dispatch:

jobs:
  call-publish:
    uses: ./.github/workflows/create_swift_package.yml
    with:
      build-debug: true
