# Publish a build for release.
name: KMMBridge-Release
on:
  workflow_dispatch:

jobs:
  call-publish:
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/create_swift_package.yml
    with:
      build-debug: false
